config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :invoices
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  validates :terms, numericality: { greater_than: 10 }
  validates :invoice_value, numericality: { greater_than: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :invoices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :destroy, :edit, :update]

  def index
    @invoices = Invoice.where(user_id: current_user.id, saved: true).order('created_at DESC')
  end

  def show
  end

  def new
    @user = current_user
    @invoice = Invoice.new
    @invoices = Invoice.where(user_id: current_user.id, saved: false)
  end

  def create
    @invoice = Invoice.new(invoice_params)
    terms = @invoice.terms
    @invoice.rate = ((terms / 10.to_f).ceil) * 0.0165
    @invoice.receivable = @invoice.invoice_value * (1 - @invoice.rate)
    @invoice.user = current_user
    @invoice.saved = true if saved_invoice?

    if @invoice.saved
      if @invoice.save
        redirect_to invoices_path
      else
        render :new
      end
    else
      if @invoice.save
        redirect_to new_invoice_path
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    @invoice.saved = true
    @invoice.update(invoice_params)
    redirect_to invoices_path
  end

  def destroy
    @invoice.destroy
    redirect_to invoices_path
  end

  private

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  def invoice_params
    params.require(:invoice).permit(:invoice_value, :terms)
  end

  def saved_invoice?
    params[:commit] == 'Salvar'
  end

  # def simulation?
  #   params[:commit] == 'Simular'
  # end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/invoices/_edit_form.html.erb
<%= simple_form_for [@invoice] do |f| %>
  <%= f.input :invoice_value, label: "Valor nominal (R$)", as: :integer, default: 0, input_html: { id: "invoice-value" } %>
  <small class="form-text text-muted">Valor mínimo de R$500,00.</small>
  <br><br>
  <%= f.input :terms, label: "Prazo de vencimento (dias)", as: :integer, default: 0, input_html: { id: "invoice-terms" } %>
  <small class="form-text text-muted">Prazo mínimo de 10 dias.</small>
  <br><br>

<div class="text-center">
  <%= link_to new_invoice_path do %>
    <div class="btn btn-default">Cancelar</div>
  <% end %>
  <%= f.button :submit, "Salvar", class: "btn btn-success button-margin" %>
  <% end %>
</div>

app/views/invoices/_form.html.erb
<div class="col-xs-8 col-xs-offset-2">
  <div class="form-group">
    <%= simple_form_for [@invoice] do |f| %>
      <%= f.input :invoice_value, label: "Valor nominal (R$)", as: :integer, default: 0, input_html: { id: "invoice-value", class: 'form-control' } %>
      <small class="form-text text-muted">Valor mínimo de R$500,00.</small>
       <br><br>
      <%= f.input :terms, label: "Prazo de vencimento (dias)", as: :integer, default: 0, input_html: { id: "invoice-terms", class: 'form-control' } %>
      <small class="form-text text-muted">Prazo mínimo de 10 dias.</small>
       <br><br>
      <div class="text-center">
        <%= f.button :submit, "Simular", class: "btn btn-default button-margin" %>
        <%= f.button :submit, "Salvar", class: "btn btn-success button-margin" %>
      </div>
    <% end %>
  </div>
</div>

app/views/invoices/edit.html.erb
<div class="container">
  <div class="navbar-space"></div>
  <div class="row">
    <div class="col-xs-12">
      <div class="col-xs-6 col-xs-offset-3">
        <div class="form-wrapper">
          <div class="form-box">
          <h2>Confirma os valores da duplicata #<%= @invoice.id %> ?</h2>
          <p>Taxa: <%= (@invoice.rate) * 100 %>% | Valor a receber: R$<%= @invoice.receivable %>
          </p>
          <%= render 'edit_form', invoice: @invoice %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/invoices/index.html.erb
<div class="container">
  <div class="navbar-space"></div>
  <% if Invoice.where(saved: true).count == 0 %>
    <div id="empty-invoices-message">
      <div class="text-center">
        <h1>Você ainda não possui duplicatas salvas.</h1>
        <p>Gostaria de fazer uma simulação e salvá-las em nosso sistema?</p>
        <%= link_to new_invoice_path do %>
          <div class="btn btn-success button-margin">Voltar para o simulador </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="text-center">
      <h1>Minhas duplicatas</h1>
    </div>
    <% @invoices.each do |invoice| %>
      <div class="row">
        <div class="col-xs-12">
          <div class="invoice-box">
            <div class="col-xs-1">
              <div class="invoice-id">
                <p>#<%= invoice.id %></p>
              </div>
            </div>
            <div class="col-xs-3">
              <div class="submit-date">
                <p>Data: <%= invoice.created_at %></p>
              </div>
            </div>
            <div class="col-xs-3">
              <p>Valor nominal: R$ <%= invoice.invoice_value %></p>
              <p>Prazo: <%= invoice.terms %></p>
            </div>
            <div class="col-xs-3">
              <p>Valor a receber: R$ <%= invoice.receivable %></p>
              <p>Taxa: <%= (invoice.rate)*100 %>%</p>
            </div>
          </div> <!-- invoice-box -->
          <div>

          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="space-footer"></div>
</div>

app/views/invoices/new.html.erb
  <div class="navbar-space"></div>
  <div class="simulator-wrapper">
    <div class="container">
    <div class="simulador">
      <div class="row">
        <div class="col-xs-12">
          <div class="col-xs-5 col-xs-offset-1">
            <div class="info-simulator">
              <div class="text-center">
                <h1>Simule o valor de suas duplicatas</h1>
                <br>
                <div class="text-left">
                  <p>Preencha os campos ao lado para simular as taxas e os valores a receber após uma operação.</p>
                  <p>As simulações serão salvas na lista abaixo e, caso tenha interesse em submetê-las a uma operação nossa, é só clicar em "Submeter", ou diretamente em "Salvar".</p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-6">
              <div class="d-flex align-content-center">
            <div class="simulator-box">
                <%= render 'form', invoice: @invoice %>
              </div>
            </div>
          </div>
        </div> <!-- col-xs-12 -->
      </div>
    </div> <!-- simulador -->
    </div>
  </div>
<% if Invoice.where(saved: false).count == 0 %>
<% else %>
  <div class="container">
    <div class="text-center">
      <h1>Minhas simulações</h1>
    </div>
      <% if @invoices.nil? %>
      <% else %>
        <% @invoices.each do |invoice| %>
          <div class="row">
            <div class="col-xs-12">
              <div class="invoice-box">
                <div class="col-xs-1">
                  <div class="invoice-id">
                    <p>#<%= invoice.id %></p>
                  </div>
                </div>
                <div class="col-xs-3">
                  <div class="submit-date">
                    <p>Data: <%= invoice.created_at %></p>
                  </div>
                </div>
                <div class="col-xs-3">
                  <p>Valor nominal: R$ <%= invoice.invoice_value %></p>
                  <p>Prazo: <%= invoice.terms %></p>
                </div>
                <div class="col-xs-3">
                  <p>Valor a receber: R$ <%= invoice.receivable %></p>
                  <p>Taxa: <%= (invoice.rate)*100 %>%</p>
                </div>
                <div class="col-xs-2">
                  <%= link_to 'Submeter', edit_invoice_path(invoice), class: 'btn btn-success', id:'submit-invoice-box' %>
                </div>
              </div> <!-- invoice-box -->
            </div> <!-- col-xs-12 -->
          </div> <!-- row -->
        <% end %>
      <% end %>
    <div class="space-footer"></div>
    <% end %>
</div>

app/views/invoices/new_not_used.html.erb
<div class="container">
  <h1>Simulador</h1>
  <%= simple_form_for [@invoice] do |f| %>
    <%= f.input :invoice_value, label: "Valor nominal", as: :integer, default: 0, input_html: { id: "invoice-value" } %>
    <%= f.input :terms, label: "Prazo de vencimento", as: :integer, default: 0, input_html: { id: "invoice-terms" } %>
  <% end %>
  <div class="btn btn-primary" id="simulator-button">Simular</div>

  <p id="simulator-rate"></p>
  <p id="simulator-receivable"></p>



</div>




<br><br><br><br><br><br><br>
<br><br><br><br><br><br><br>
<br><br><br><br><br><br><br>
<div class="container">
  <%= render 'form', invoice: @invoice %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>$ AccRec Simulator</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="stick-footer">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="banner" alt="banner - Photo by rawpixel on Unsplash">
  <div class="banner-box">
    <div class="h1-message">
      <h1>Sua empresa precisa de fôle
      go financeiro?</h1>
      <p>Ajudamos a financiar os recebíveis da sua empresa</p>
    </div>
    <% if user_signed_in? %>
    <%= link_to new_invoice_path do %>
          <div class="btn btn-success button-margin">Comece com uma simulação </div>
        <% end %>
    <% else %>
     <%= link_to new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <div class="btn btn-warning button-margin button-padding">Cadastro grátis</div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/camilamiz" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://instagram.com/camilamizu.tattoo" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.linkedin.com/in/camila-mizumoto-65004132/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Este projeto é uma solução desenvolvida por Camila Mizumoto para um code challenge.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand", id: "logo" do %>
    <%= image_tag "logo.png", height: 70 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <%= link_to "Simulador", new_invoice_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Minhas duplicatas", invoices_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-link">Meu cadastro</a> -->
    <%= button_to destroy_user_session_path, class:"btn btn-warning", id: "sign-out-button", method: :delete do %>
      <%= t(".sign_out", default: "Log out") %>
    <% end %>

    <% else %>
        <%= link_to t(".sign_in", default: "Já sou cliente"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <div class="btn btn-success button-margin button-padding", id="sign-in-button">Abra sua conta gratuita</div>
        <% end %>
    <% end %>
  </div>


  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">

  </div>
</div>